---
abstract: 'CPAN Test Dummy that has multiple packages in one file with different versions'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.017
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Test-Dummy-MultiPkgVer-NoMETA
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/miyagawa/CPAN-Test-Dummy-MultiPkgVer-NoMETA/issues
  homepage: https://github.com/miyagawa/CPAN-Test-Dummy-MultiPkgVer-NoMETA
  repository: https://github.com/miyagawa/CPAN-Test-Dummy-MultiPkgVer-NoMETA.git
version: 0.01
